#!/usr/bin/env node

'use strict';
const path = require('path');
const { exec } = require('child_process');
const minimist = require('minimist');

const params = minimist(process.argv.slice(2));
const folder = path.join(process.env.PWD, params.f || params.folder || 'mock');
const port = params.p || params.port || 3000;
const server = `${__dirname}/server.js`;

const child = exec(`nodemon --watch ${folder} --ignore "db/*.json" ${server} ${folder} ${port}`);

child.stdout.on('data', data => console.log(String(data)));
child.stderr.on('data', data => console.error(String(data)));
child.on('close', code => process.exit(code));
